# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GmvHHLpsndGJK5ckqvSqCBr0nnUKCzAM
"""

def f():
  return 1

def g():
  return 2

